server:
  port: 8080

spring:
  application:
    name: ShardingsphereDemo
  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings: false
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yml
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.8.12:10000
        namespace: 549d6c1b-be80-4ece-a300-7cbaec840f0a
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
#      config:
#        enabled: false
